// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.17.3
// source: encoding.go

package msm

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 0
	_ uint = 0 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__SimplexEpochInfo__PChainReferenceHeight     = 1
	canoto__SimplexEpochInfo__EpochNumber               = 2
	canoto__SimplexEpochInfo__PrevSealingBlockHash      = 3
	canoto__SimplexEpochInfo__NextPChainReferenceHeight = 4
	canoto__SimplexEpochInfo__PrevVMBlockSeq            = 5
	canoto__SimplexEpochInfo__BlockValidationDescriptor = 6
	canoto__SimplexEpochInfo__NextEpochApprovals        = 7
	canoto__SimplexEpochInfo__SealingBlockSeq           = 8

	canoto__SimplexEpochInfo__PChainReferenceHeight__tag     = "\x08" // canoto.Tag(canoto__SimplexEpochInfo__PChainReferenceHeight, canoto.Varint)
	canoto__SimplexEpochInfo__EpochNumber__tag               = "\x10" // canoto.Tag(canoto__SimplexEpochInfo__EpochNumber, canoto.Varint)
	canoto__SimplexEpochInfo__PrevSealingBlockHash__tag      = "\x1a" // canoto.Tag(canoto__SimplexEpochInfo__PrevSealingBlockHash, canoto.Len)
	canoto__SimplexEpochInfo__NextPChainReferenceHeight__tag = "\x20" // canoto.Tag(canoto__SimplexEpochInfo__NextPChainReferenceHeight, canoto.Varint)
	canoto__SimplexEpochInfo__PrevVMBlockSeq__tag            = "\x28" // canoto.Tag(canoto__SimplexEpochInfo__PrevVMBlockSeq, canoto.Varint)
	canoto__SimplexEpochInfo__BlockValidationDescriptor__tag = "\x32" // canoto.Tag(canoto__SimplexEpochInfo__BlockValidationDescriptor, canoto.Len)
	canoto__SimplexEpochInfo__NextEpochApprovals__tag        = "\x3a" // canoto.Tag(canoto__SimplexEpochInfo__NextEpochApprovals, canoto.Len)
	canoto__SimplexEpochInfo__SealingBlockSeq__tag           = "\x40" // canoto.Tag(canoto__SimplexEpochInfo__SealingBlockSeq, canoto.Varint)
)

type canotoData_SimplexEpochInfo struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*SimplexEpochInfo) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(SimplexEpochInfo{}))
	var zero SimplexEpochInfo
	s := &canoto.Spec{
		Name: "SimplexEpochInfo",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canoto__SimplexEpochInfo__PChainReferenceHeight,
				Name:        "PChainReferenceHeight",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.PChainReferenceHeight),
			},
			{
				FieldNumber: canoto__SimplexEpochInfo__EpochNumber,
				Name:        "EpochNumber",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.EpochNumber),
			},
			{
				FieldNumber: canoto__SimplexEpochInfo__PrevSealingBlockHash,
				Name:        "PrevSealingBlockHash",
				OneOf:       "",
				TypeBytes:   true,
			},
			{
				FieldNumber: canoto__SimplexEpochInfo__NextPChainReferenceHeight,
				Name:        "NextPChainReferenceHeight",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.NextPChainReferenceHeight),
			},
			{
				FieldNumber: canoto__SimplexEpochInfo__PrevVMBlockSeq,
				Name:        "PrevVMBlockSeq",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.PrevVMBlockSeq),
			},
			canoto.FieldTypeFromField(
				/*type inference:*/ zero.BlockValidationDescriptor,
				/*FieldNumber:   */ canoto__SimplexEpochInfo__BlockValidationDescriptor,
				/*Name:          */ "BlockValidationDescriptor",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			canoto.FieldTypeFromField(
				/*type inference:*/ zero.NextEpochApprovals,
				/*FieldNumber:   */ canoto__SimplexEpochInfo__NextEpochApprovals,
				/*Name:          */ "NextEpochApprovals",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			{
				FieldNumber: canoto__SimplexEpochInfo__SealingBlockSeq,
				Name:        "SealingBlockSeq",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.SealingBlockSeq),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*SimplexEpochInfo) MakeCanoto() *SimplexEpochInfo {
	return new(SimplexEpochInfo)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *SimplexEpochInfo) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *SimplexEpochInfo) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = SimplexEpochInfo{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__SimplexEpochInfo__PChainReferenceHeight:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.PChainReferenceHeight); err != nil {
				return err
			}
			if canoto.IsZero(c.PChainReferenceHeight) {
				return canoto.ErrZeroValue
			}
		case canoto__SimplexEpochInfo__EpochNumber:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.EpochNumber); err != nil {
				return err
			}
			if canoto.IsZero(c.EpochNumber) {
				return canoto.ErrZeroValue
			}
		case canoto__SimplexEpochInfo__PrevSealingBlockHash:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.PrevSealingBlockHash); err != nil {
				return err
			}
			if len(c.PrevSealingBlockHash) == 0 {
				return canoto.ErrZeroValue
			}
		case canoto__SimplexEpochInfo__NextPChainReferenceHeight:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.NextPChainReferenceHeight); err != nil {
				return err
			}
			if canoto.IsZero(c.NextPChainReferenceHeight) {
				return canoto.ErrZeroValue
			}
		case canoto__SimplexEpochInfo__PrevVMBlockSeq:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.PrevVMBlockSeq); err != nil {
				return err
			}
			if canoto.IsZero(c.PrevVMBlockSeq) {
				return canoto.ErrZeroValue
			}
		case canoto__SimplexEpochInfo__BlockValidationDescriptor:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.BlockValidationDescriptor = c.BlockValidationDescriptor.MakeCanoto()
			if err := c.BlockValidationDescriptor.UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		case canoto__SimplexEpochInfo__NextEpochApprovals:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.NextEpochApprovals = c.NextEpochApprovals.MakeCanoto()
			if err := c.NextEpochApprovals.UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		case canoto__SimplexEpochInfo__SealingBlockSeq:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.SealingBlockSeq); err != nil {
				return err
			}
			if canoto.IsZero(c.SealingBlockSeq) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *SimplexEpochInfo) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if !c.BlockValidationDescriptor.ValidCanoto() {
		return false
	}
	if !c.NextEpochApprovals.ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *SimplexEpochInfo) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.PChainReferenceHeight) {
		size += uint64(len(canoto__SimplexEpochInfo__PChainReferenceHeight__tag)) + canoto.SizeUint(c.PChainReferenceHeight)
	}
	if !canoto.IsZero(c.EpochNumber) {
		size += uint64(len(canoto__SimplexEpochInfo__EpochNumber__tag)) + canoto.SizeUint(c.EpochNumber)
	}
	if len(c.PrevSealingBlockHash) != 0 {
		size += uint64(len(canoto__SimplexEpochInfo__PrevSealingBlockHash__tag)) + canoto.SizeBytes(c.PrevSealingBlockHash)
	}
	if !canoto.IsZero(c.NextPChainReferenceHeight) {
		size += uint64(len(canoto__SimplexEpochInfo__NextPChainReferenceHeight__tag)) + canoto.SizeUint(c.NextPChainReferenceHeight)
	}
	if !canoto.IsZero(c.PrevVMBlockSeq) {
		size += uint64(len(canoto__SimplexEpochInfo__PrevVMBlockSeq__tag)) + canoto.SizeUint(c.PrevVMBlockSeq)
	}
	c.BlockValidationDescriptor.CalculateCanotoCache()
	if fieldSize := c.BlockValidationDescriptor.CachedCanotoSize(); fieldSize != 0 {
		size += uint64(len(canoto__SimplexEpochInfo__BlockValidationDescriptor__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	c.NextEpochApprovals.CalculateCanotoCache()
	if fieldSize := c.NextEpochApprovals.CachedCanotoSize(); fieldSize != 0 {
		size += uint64(len(canoto__SimplexEpochInfo__NextEpochApprovals__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	if !canoto.IsZero(c.SealingBlockSeq) {
		size += uint64(len(canoto__SimplexEpochInfo__SealingBlockSeq__tag)) + canoto.SizeUint(c.SealingBlockSeq)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *SimplexEpochInfo) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *SimplexEpochInfo) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *SimplexEpochInfo) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.PChainReferenceHeight) {
		canoto.Append(&w, canoto__SimplexEpochInfo__PChainReferenceHeight__tag)
		canoto.AppendUint(&w, c.PChainReferenceHeight)
	}
	if !canoto.IsZero(c.EpochNumber) {
		canoto.Append(&w, canoto__SimplexEpochInfo__EpochNumber__tag)
		canoto.AppendUint(&w, c.EpochNumber)
	}
	if len(c.PrevSealingBlockHash) != 0 {
		canoto.Append(&w, canoto__SimplexEpochInfo__PrevSealingBlockHash__tag)
		canoto.AppendBytes(&w, c.PrevSealingBlockHash)
	}
	if !canoto.IsZero(c.NextPChainReferenceHeight) {
		canoto.Append(&w, canoto__SimplexEpochInfo__NextPChainReferenceHeight__tag)
		canoto.AppendUint(&w, c.NextPChainReferenceHeight)
	}
	if !canoto.IsZero(c.PrevVMBlockSeq) {
		canoto.Append(&w, canoto__SimplexEpochInfo__PrevVMBlockSeq__tag)
		canoto.AppendUint(&w, c.PrevVMBlockSeq)
	}
	if fieldSize := c.BlockValidationDescriptor.CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__SimplexEpochInfo__BlockValidationDescriptor__tag)
		canoto.AppendUint(&w, fieldSize)
		w = c.BlockValidationDescriptor.MarshalCanotoInto(w)
	}
	if fieldSize := c.NextEpochApprovals.CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__SimplexEpochInfo__NextEpochApprovals__tag)
		canoto.AppendUint(&w, fieldSize)
		w = c.NextEpochApprovals.MarshalCanotoInto(w)
	}
	if !canoto.IsZero(c.SealingBlockSeq) {
		canoto.Append(&w, canoto__SimplexEpochInfo__SealingBlockSeq__tag)
		canoto.AppendUint(&w, c.SealingBlockSeq)
	}
	return w
}

const (
	canoto__BlockValidationDescriptor__AggregatedMembership = 1

	canoto__BlockValidationDescriptor__AggregatedMembership__tag = "\x0a" // canoto.Tag(canoto__BlockValidationDescriptor__AggregatedMembership, canoto.Len)
)

type canotoData_BlockValidationDescriptor struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*BlockValidationDescriptor) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(BlockValidationDescriptor{}))
	var zero BlockValidationDescriptor
	s := &canoto.Spec{
		Name: "BlockValidationDescriptor",
		Fields: []canoto.FieldType{
			canoto.FieldTypeFromField(
				/*type inference:*/ zero.AggregatedMembership,
				/*FieldNumber:   */ canoto__BlockValidationDescriptor__AggregatedMembership,
				/*Name:          */ "AggregatedMembership",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*BlockValidationDescriptor) MakeCanoto() *BlockValidationDescriptor {
	return new(BlockValidationDescriptor)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *BlockValidationDescriptor) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *BlockValidationDescriptor) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = BlockValidationDescriptor{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__BlockValidationDescriptor__AggregatedMembership:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.AggregatedMembership = c.AggregatedMembership.MakeCanoto()
			if err := c.AggregatedMembership.UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *BlockValidationDescriptor) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if !c.AggregatedMembership.ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *BlockValidationDescriptor) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	c.AggregatedMembership.CalculateCanotoCache()
	if fieldSize := c.AggregatedMembership.CachedCanotoSize(); fieldSize != 0 {
		size += uint64(len(canoto__BlockValidationDescriptor__AggregatedMembership__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *BlockValidationDescriptor) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *BlockValidationDescriptor) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *BlockValidationDescriptor) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if fieldSize := c.AggregatedMembership.CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__BlockValidationDescriptor__AggregatedMembership__tag)
		canoto.AppendUint(&w, fieldSize)
		w = c.AggregatedMembership.MarshalCanotoInto(w)
	}
	return w
}

const (
	canoto__AggregatedMembership__Members = 1

	canoto__AggregatedMembership__Members__tag = "\x0a" // canoto.Tag(canoto__AggregatedMembership__Members, canoto.Len)
)

type canotoData_AggregatedMembership struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*AggregatedMembership) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(AggregatedMembership{}))
	var zero AggregatedMembership
	s := &canoto.Spec{
		Name: "AggregatedMembership",
		Fields: []canoto.FieldType{
			canoto.FieldTypeFromField(
				/*type inference:*/ zero.Members,
				/*FieldNumber:   */ canoto__AggregatedMembership__Members,
				/*Name:          */ "Members",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*AggregatedMembership) MakeCanoto() *AggregatedMembership {
	return new(AggregatedMembership)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *AggregatedMembership) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *AggregatedMembership) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = AggregatedMembership{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__AggregatedMembership__Members:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.Members = c.Members.MakeCanoto()
			if err := c.Members.UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *AggregatedMembership) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if !c.Members.ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *AggregatedMembership) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	c.Members.CalculateCanotoCache()
	if fieldSize := c.Members.CachedCanotoSize(); fieldSize != 0 {
		size += uint64(len(canoto__AggregatedMembership__Members__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *AggregatedMembership) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AggregatedMembership) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AggregatedMembership) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if fieldSize := c.Members.CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__AggregatedMembership__Members__tag)
		canoto.AppendUint(&w, fieldSize)
		w = c.Members.MarshalCanotoInto(w)
	}
	return w
}

const (
	canoto__NextEpochApprovals__NodeIDs   = 1
	canoto__NextEpochApprovals__Signature = 2

	canoto__NextEpochApprovals__NodeIDs__tag   = "\x0a" // canoto.Tag(canoto__NextEpochApprovals__NodeIDs, canoto.Len)
	canoto__NextEpochApprovals__Signature__tag = "\x12" // canoto.Tag(canoto__NextEpochApprovals__Signature, canoto.Len)
)

type canotoData_NextEpochApprovals struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*NextEpochApprovals) CanotoSpec(...reflect.Type) *canoto.Spec {
	s := &canoto.Spec{
		Name: "NextEpochApprovals",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canoto__NextEpochApprovals__NodeIDs,
				Name:        "NodeIDs",
				OneOf:       "",
				TypeBytes:   true,
			},
			{
				FieldNumber: canoto__NextEpochApprovals__Signature,
				Name:        "Signature",
				OneOf:       "",
				TypeBytes:   true,
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*NextEpochApprovals) MakeCanoto() *NextEpochApprovals {
	return new(NextEpochApprovals)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *NextEpochApprovals) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *NextEpochApprovals) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = NextEpochApprovals{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__NextEpochApprovals__NodeIDs:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.NodeIDs); err != nil {
				return err
			}
			if len(c.NodeIDs) == 0 {
				return canoto.ErrZeroValue
			}
		case canoto__NextEpochApprovals__Signature:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.Signature); err != nil {
				return err
			}
			if len(c.Signature) == 0 {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *NextEpochApprovals) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *NextEpochApprovals) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if len(c.NodeIDs) != 0 {
		size += uint64(len(canoto__NextEpochApprovals__NodeIDs__tag)) + canoto.SizeBytes(c.NodeIDs)
	}
	if len(c.Signature) != 0 {
		size += uint64(len(canoto__NextEpochApprovals__Signature__tag)) + canoto.SizeBytes(c.Signature)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *NextEpochApprovals) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *NextEpochApprovals) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *NextEpochApprovals) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if len(c.NodeIDs) != 0 {
		canoto.Append(&w, canoto__NextEpochApprovals__NodeIDs__tag)
		canoto.AppendBytes(&w, c.NodeIDs)
	}
	if len(c.Signature) != 0 {
		canoto.Append(&w, canoto__NextEpochApprovals__Signature__tag)
		canoto.AppendBytes(&w, c.Signature)
	}
	return w
}
