// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.17.3
// source: encoding.go

package metadata

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 0
	_ uint = 0 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__OuterBlock__InnerBlock = 1
	canoto__OuterBlock__Metadata   = 2

	canoto__OuterBlock__InnerBlock__tag = "\x0a" // canoto.Tag(canoto__OuterBlock__InnerBlock, canoto.Len)
	canoto__OuterBlock__Metadata__tag   = "\x12" // canoto.Tag(canoto__OuterBlock__Metadata, canoto.Len)
)

type canotoData_OuterBlock struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*OuterBlock) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(OuterBlock{}))
	var zero OuterBlock
	s := &canoto.Spec{
		Name: "OuterBlock",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canoto__OuterBlock__InnerBlock,
				Name:        "InnerBlock",
				OneOf:       "",
				TypeBytes:   true,
			},
			canoto.FieldTypeFromField(
				/*type inference:*/ (&zero.Metadata),
				/*FieldNumber:   */ canoto__OuterBlock__Metadata,
				/*Name:          */ "Metadata",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*OuterBlock) MakeCanoto() *OuterBlock {
	return new(OuterBlock)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *OuterBlock) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *OuterBlock) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = OuterBlock{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__OuterBlock__InnerBlock:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.InnerBlock); err != nil {
				return err
			}
			if len(c.InnerBlock) == 0 {
				return canoto.ErrZeroValue
			}
		case canoto__OuterBlock__Metadata:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			if err := (&c.Metadata).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *OuterBlock) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if !(&c.Metadata).ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *OuterBlock) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if len(c.InnerBlock) != 0 {
		size += uint64(len(canoto__OuterBlock__InnerBlock__tag)) + canoto.SizeBytes(c.InnerBlock)
	}
	(&c.Metadata).CalculateCanotoCache()
	if fieldSize := (&c.Metadata).CachedCanotoSize(); fieldSize != 0 {
		size += uint64(len(canoto__OuterBlock__Metadata__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *OuterBlock) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *OuterBlock) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *OuterBlock) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if len(c.InnerBlock) != 0 {
		canoto.Append(&w, canoto__OuterBlock__InnerBlock__tag)
		canoto.AppendBytes(&w, c.InnerBlock)
	}
	if fieldSize := (&c.Metadata).CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__OuterBlock__Metadata__tag)
		canoto.AppendUint(&w, fieldSize)
		w = (&c.Metadata).MarshalCanotoInto(w)
	}
	return w
}

const (
	canoto__StateMachineMetadata__ICMEpochInfo            = 1
	canoto__StateMachineMetadata__SimplexEpochInfo        = 2
	canoto__StateMachineMetadata__SimplexProtocolMetadata = 3
	canoto__StateMachineMetadata__SimplexBlacklist        = 4
	canoto__StateMachineMetadata__AuxiliaryInfo           = 5
	canoto__StateMachineMetadata__PChainHeight            = 6
	canoto__StateMachineMetadata__Timestamp               = 7

	canoto__StateMachineMetadata__ICMEpochInfo__tag            = "\x0a" // canoto.Tag(canoto__StateMachineMetadata__ICMEpochInfo, canoto.Len)
	canoto__StateMachineMetadata__SimplexEpochInfo__tag        = "\x12" // canoto.Tag(canoto__StateMachineMetadata__SimplexEpochInfo, canoto.Len)
	canoto__StateMachineMetadata__SimplexProtocolMetadata__tag = "\x1a" // canoto.Tag(canoto__StateMachineMetadata__SimplexProtocolMetadata, canoto.Len)
	canoto__StateMachineMetadata__SimplexBlacklist__tag        = "\x22" // canoto.Tag(canoto__StateMachineMetadata__SimplexBlacklist, canoto.Len)
	canoto__StateMachineMetadata__AuxiliaryInfo__tag           = "\x2a" // canoto.Tag(canoto__StateMachineMetadata__AuxiliaryInfo, canoto.Len)
	canoto__StateMachineMetadata__PChainHeight__tag            = "\x30" // canoto.Tag(canoto__StateMachineMetadata__PChainHeight, canoto.Varint)
	canoto__StateMachineMetadata__Timestamp__tag               = "\x38" // canoto.Tag(canoto__StateMachineMetadata__Timestamp, canoto.Varint)
)

type canotoData_StateMachineMetadata struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*StateMachineMetadata) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(StateMachineMetadata{}))
	var zero StateMachineMetadata
	s := &canoto.Spec{
		Name: "StateMachineMetadata",
		Fields: []canoto.FieldType{
			canoto.FieldTypeFromField(
				/*type inference:*/ (&zero.ICMEpochInfo),
				/*FieldNumber:   */ canoto__StateMachineMetadata__ICMEpochInfo,
				/*Name:          */ "ICMEpochInfo",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			canoto.FieldTypeFromField(
				/*type inference:*/ (&zero.SimplexEpochInfo),
				/*FieldNumber:   */ canoto__StateMachineMetadata__SimplexEpochInfo,
				/*Name:          */ "SimplexEpochInfo",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			{
				FieldNumber: canoto__StateMachineMetadata__SimplexProtocolMetadata,
				Name:        "SimplexProtocolMetadata",
				OneOf:       "",
				TypeBytes:   true,
			},
			{
				FieldNumber: canoto__StateMachineMetadata__SimplexBlacklist,
				Name:        "SimplexBlacklist",
				OneOf:       "",
				TypeBytes:   true,
			},
			canoto.FieldTypeFromField(
				/*type inference:*/ (zero.AuxiliaryInfo),
				/*FieldNumber:   */ canoto__StateMachineMetadata__AuxiliaryInfo,
				/*Name:          */ "AuxiliaryInfo",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			{
				FieldNumber: canoto__StateMachineMetadata__PChainHeight,
				Name:        "PChainHeight",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.PChainHeight),
			},
			{
				FieldNumber: canoto__StateMachineMetadata__Timestamp,
				Name:        "Timestamp",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.Timestamp),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*StateMachineMetadata) MakeCanoto() *StateMachineMetadata {
	return new(StateMachineMetadata)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *StateMachineMetadata) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *StateMachineMetadata) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = StateMachineMetadata{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__StateMachineMetadata__ICMEpochInfo:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			if err := (&c.ICMEpochInfo).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		case canoto__StateMachineMetadata__SimplexEpochInfo:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			if err := (&c.SimplexEpochInfo).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		case canoto__StateMachineMetadata__SimplexProtocolMetadata:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.SimplexProtocolMetadata); err != nil {
				return err
			}
			if len(c.SimplexProtocolMetadata) == 0 {
				return canoto.ErrZeroValue
			}
		case canoto__StateMachineMetadata__SimplexBlacklist:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.SimplexBlacklist); err != nil {
				return err
			}
			if len(c.SimplexBlacklist) == 0 {
				return canoto.ErrZeroValue
			}
		case canoto__StateMachineMetadata__AuxiliaryInfo:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.AuxiliaryInfo = canoto.MakePointer(c.AuxiliaryInfo)
			if err := (c.AuxiliaryInfo).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		case canoto__StateMachineMetadata__PChainHeight:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.PChainHeight); err != nil {
				return err
			}
			if canoto.IsZero(c.PChainHeight) {
				return canoto.ErrZeroValue
			}
		case canoto__StateMachineMetadata__Timestamp:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.Timestamp); err != nil {
				return err
			}
			if canoto.IsZero(c.Timestamp) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *StateMachineMetadata) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if !(&c.ICMEpochInfo).ValidCanoto() {
		return false
	}
	if !(&c.SimplexEpochInfo).ValidCanoto() {
		return false
	}
	if c.AuxiliaryInfo != nil && !(c.AuxiliaryInfo).ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *StateMachineMetadata) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	(&c.ICMEpochInfo).CalculateCanotoCache()
	if fieldSize := (&c.ICMEpochInfo).CachedCanotoSize(); fieldSize != 0 {
		size += uint64(len(canoto__StateMachineMetadata__ICMEpochInfo__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	(&c.SimplexEpochInfo).CalculateCanotoCache()
	if fieldSize := (&c.SimplexEpochInfo).CachedCanotoSize(); fieldSize != 0 {
		size += uint64(len(canoto__StateMachineMetadata__SimplexEpochInfo__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	if len(c.SimplexProtocolMetadata) != 0 {
		size += uint64(len(canoto__StateMachineMetadata__SimplexProtocolMetadata__tag)) + canoto.SizeBytes(c.SimplexProtocolMetadata)
	}
	if len(c.SimplexBlacklist) != 0 {
		size += uint64(len(canoto__StateMachineMetadata__SimplexBlacklist__tag)) + canoto.SizeBytes(c.SimplexBlacklist)
	}
	if c.AuxiliaryInfo != nil {
		(c.AuxiliaryInfo).CalculateCanotoCache()
		if fieldSize := (c.AuxiliaryInfo).CachedCanotoSize(); fieldSize != 0 {
			size += uint64(len(canoto__StateMachineMetadata__AuxiliaryInfo__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	if !canoto.IsZero(c.PChainHeight) {
		size += uint64(len(canoto__StateMachineMetadata__PChainHeight__tag)) + canoto.SizeUint(c.PChainHeight)
	}
	if !canoto.IsZero(c.Timestamp) {
		size += uint64(len(canoto__StateMachineMetadata__Timestamp__tag)) + canoto.SizeUint(c.Timestamp)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *StateMachineMetadata) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *StateMachineMetadata) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *StateMachineMetadata) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if fieldSize := (&c.ICMEpochInfo).CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__StateMachineMetadata__ICMEpochInfo__tag)
		canoto.AppendUint(&w, fieldSize)
		w = (&c.ICMEpochInfo).MarshalCanotoInto(w)
	}
	if fieldSize := (&c.SimplexEpochInfo).CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__StateMachineMetadata__SimplexEpochInfo__tag)
		canoto.AppendUint(&w, fieldSize)
		w = (&c.SimplexEpochInfo).MarshalCanotoInto(w)
	}
	if len(c.SimplexProtocolMetadata) != 0 {
		canoto.Append(&w, canoto__StateMachineMetadata__SimplexProtocolMetadata__tag)
		canoto.AppendBytes(&w, c.SimplexProtocolMetadata)
	}
	if len(c.SimplexBlacklist) != 0 {
		canoto.Append(&w, canoto__StateMachineMetadata__SimplexBlacklist__tag)
		canoto.AppendBytes(&w, c.SimplexBlacklist)
	}
	if c.AuxiliaryInfo != nil {
		if fieldSize := (c.AuxiliaryInfo).CachedCanotoSize(); fieldSize != 0 {
			canoto.Append(&w, canoto__StateMachineMetadata__AuxiliaryInfo__tag)
			canoto.AppendUint(&w, fieldSize)
			w = (c.AuxiliaryInfo).MarshalCanotoInto(w)
		}
	}
	if !canoto.IsZero(c.PChainHeight) {
		canoto.Append(&w, canoto__StateMachineMetadata__PChainHeight__tag)
		canoto.AppendUint(&w, c.PChainHeight)
	}
	if !canoto.IsZero(c.Timestamp) {
		canoto.Append(&w, canoto__StateMachineMetadata__Timestamp__tag)
		canoto.AppendUint(&w, c.Timestamp)
	}
	return w
}

const (
	canoto__ICMEpochInfo__EpochStartTime    = 1
	canoto__ICMEpochInfo__EpochNumber       = 2
	canoto__ICMEpochInfo__PChainEpochHeight = 3

	canoto__ICMEpochInfo__EpochStartTime__tag    = "\x08" // canoto.Tag(canoto__ICMEpochInfo__EpochStartTime, canoto.Varint)
	canoto__ICMEpochInfo__EpochNumber__tag       = "\x10" // canoto.Tag(canoto__ICMEpochInfo__EpochNumber, canoto.Varint)
	canoto__ICMEpochInfo__PChainEpochHeight__tag = "\x18" // canoto.Tag(canoto__ICMEpochInfo__PChainEpochHeight, canoto.Varint)
)

type canotoData_ICMEpochInfo struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*ICMEpochInfo) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero ICMEpochInfo
	s := &canoto.Spec{
		Name: "ICMEpochInfo",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canoto__ICMEpochInfo__EpochStartTime,
				Name:        "EpochStartTime",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.EpochStartTime),
			},
			{
				FieldNumber: canoto__ICMEpochInfo__EpochNumber,
				Name:        "EpochNumber",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.EpochNumber),
			},
			{
				FieldNumber: canoto__ICMEpochInfo__PChainEpochHeight,
				Name:        "PChainEpochHeight",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.PChainEpochHeight),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*ICMEpochInfo) MakeCanoto() *ICMEpochInfo {
	return new(ICMEpochInfo)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *ICMEpochInfo) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *ICMEpochInfo) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = ICMEpochInfo{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__ICMEpochInfo__EpochStartTime:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.EpochStartTime); err != nil {
				return err
			}
			if canoto.IsZero(c.EpochStartTime) {
				return canoto.ErrZeroValue
			}
		case canoto__ICMEpochInfo__EpochNumber:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.EpochNumber); err != nil {
				return err
			}
			if canoto.IsZero(c.EpochNumber) {
				return canoto.ErrZeroValue
			}
		case canoto__ICMEpochInfo__PChainEpochHeight:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.PChainEpochHeight); err != nil {
				return err
			}
			if canoto.IsZero(c.PChainEpochHeight) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *ICMEpochInfo) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *ICMEpochInfo) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.EpochStartTime) {
		size += uint64(len(canoto__ICMEpochInfo__EpochStartTime__tag)) + canoto.SizeUint(c.EpochStartTime)
	}
	if !canoto.IsZero(c.EpochNumber) {
		size += uint64(len(canoto__ICMEpochInfo__EpochNumber__tag)) + canoto.SizeUint(c.EpochNumber)
	}
	if !canoto.IsZero(c.PChainEpochHeight) {
		size += uint64(len(canoto__ICMEpochInfo__PChainEpochHeight__tag)) + canoto.SizeUint(c.PChainEpochHeight)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *ICMEpochInfo) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *ICMEpochInfo) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *ICMEpochInfo) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.EpochStartTime) {
		canoto.Append(&w, canoto__ICMEpochInfo__EpochStartTime__tag)
		canoto.AppendUint(&w, c.EpochStartTime)
	}
	if !canoto.IsZero(c.EpochNumber) {
		canoto.Append(&w, canoto__ICMEpochInfo__EpochNumber__tag)
		canoto.AppendUint(&w, c.EpochNumber)
	}
	if !canoto.IsZero(c.PChainEpochHeight) {
		canoto.Append(&w, canoto__ICMEpochInfo__PChainEpochHeight__tag)
		canoto.AppendUint(&w, c.PChainEpochHeight)
	}
	return w
}

const (
	canoto__AuxiliaryInfo__Info           = 1
	canoto__AuxiliaryInfo__PrevAuxInfoSeq = 2
	canoto__AuxiliaryInfo__ApplicationID  = 3

	canoto__AuxiliaryInfo__Info__tag           = "\x0a" // canoto.Tag(canoto__AuxiliaryInfo__Info, canoto.Len)
	canoto__AuxiliaryInfo__PrevAuxInfoSeq__tag = "\x10" // canoto.Tag(canoto__AuxiliaryInfo__PrevAuxInfoSeq, canoto.Varint)
	canoto__AuxiliaryInfo__ApplicationID__tag  = "\x18" // canoto.Tag(canoto__AuxiliaryInfo__ApplicationID, canoto.Varint)
)

type canotoData_AuxiliaryInfo struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*AuxiliaryInfo) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero AuxiliaryInfo
	s := &canoto.Spec{
		Name: "AuxiliaryInfo",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canoto__AuxiliaryInfo__Info,
				Name:        "Info",
				OneOf:       "",
				TypeBytes:   true,
			},
			{
				FieldNumber: canoto__AuxiliaryInfo__PrevAuxInfoSeq,
				Name:        "PrevAuxInfoSeq",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.PrevAuxInfoSeq),
			},
			{
				FieldNumber: canoto__AuxiliaryInfo__ApplicationID,
				Name:        "ApplicationID",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.ApplicationID),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*AuxiliaryInfo) MakeCanoto() *AuxiliaryInfo {
	return new(AuxiliaryInfo)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *AuxiliaryInfo) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *AuxiliaryInfo) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = AuxiliaryInfo{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__AuxiliaryInfo__Info:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.Info); err != nil {
				return err
			}
			if len(c.Info) == 0 {
				return canoto.ErrZeroValue
			}
		case canoto__AuxiliaryInfo__PrevAuxInfoSeq:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.PrevAuxInfoSeq); err != nil {
				return err
			}
			if canoto.IsZero(c.PrevAuxInfoSeq) {
				return canoto.ErrZeroValue
			}
		case canoto__AuxiliaryInfo__ApplicationID:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.ApplicationID); err != nil {
				return err
			}
			if canoto.IsZero(c.ApplicationID) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *AuxiliaryInfo) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *AuxiliaryInfo) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if len(c.Info) != 0 {
		size += uint64(len(canoto__AuxiliaryInfo__Info__tag)) + canoto.SizeBytes(c.Info)
	}
	if !canoto.IsZero(c.PrevAuxInfoSeq) {
		size += uint64(len(canoto__AuxiliaryInfo__PrevAuxInfoSeq__tag)) + canoto.SizeUint(c.PrevAuxInfoSeq)
	}
	if !canoto.IsZero(c.ApplicationID) {
		size += uint64(len(canoto__AuxiliaryInfo__ApplicationID__tag)) + canoto.SizeUint(c.ApplicationID)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *AuxiliaryInfo) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AuxiliaryInfo) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AuxiliaryInfo) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if len(c.Info) != 0 {
		canoto.Append(&w, canoto__AuxiliaryInfo__Info__tag)
		canoto.AppendBytes(&w, c.Info)
	}
	if !canoto.IsZero(c.PrevAuxInfoSeq) {
		canoto.Append(&w, canoto__AuxiliaryInfo__PrevAuxInfoSeq__tag)
		canoto.AppendUint(&w, c.PrevAuxInfoSeq)
	}
	if !canoto.IsZero(c.ApplicationID) {
		canoto.Append(&w, canoto__AuxiliaryInfo__ApplicationID__tag)
		canoto.AppendUint(&w, c.ApplicationID)
	}
	return w
}

const (
	canoto__SimplexEpochInfo__PChainReferenceHeight     = 1
	canoto__SimplexEpochInfo__EpochNumber               = 2
	canoto__SimplexEpochInfo__PrevSealingBlockHash      = 3
	canoto__SimplexEpochInfo__NextPChainReferenceHeight = 4
	canoto__SimplexEpochInfo__PrevVMBlockSeq            = 5
	canoto__SimplexEpochInfo__BlockValidationDescriptor = 6
	canoto__SimplexEpochInfo__NextEpochApprovals        = 7
	canoto__SimplexEpochInfo__SealingBlockSeq           = 8

	canoto__SimplexEpochInfo__PChainReferenceHeight__tag     = "\x08" // canoto.Tag(canoto__SimplexEpochInfo__PChainReferenceHeight, canoto.Varint)
	canoto__SimplexEpochInfo__EpochNumber__tag               = "\x10" // canoto.Tag(canoto__SimplexEpochInfo__EpochNumber, canoto.Varint)
	canoto__SimplexEpochInfo__PrevSealingBlockHash__tag      = "\x1a" // canoto.Tag(canoto__SimplexEpochInfo__PrevSealingBlockHash, canoto.Len)
	canoto__SimplexEpochInfo__NextPChainReferenceHeight__tag = "\x20" // canoto.Tag(canoto__SimplexEpochInfo__NextPChainReferenceHeight, canoto.Varint)
	canoto__SimplexEpochInfo__PrevVMBlockSeq__tag            = "\x28" // canoto.Tag(canoto__SimplexEpochInfo__PrevVMBlockSeq, canoto.Varint)
	canoto__SimplexEpochInfo__BlockValidationDescriptor__tag = "\x32" // canoto.Tag(canoto__SimplexEpochInfo__BlockValidationDescriptor, canoto.Len)
	canoto__SimplexEpochInfo__NextEpochApprovals__tag        = "\x3a" // canoto.Tag(canoto__SimplexEpochInfo__NextEpochApprovals, canoto.Len)
	canoto__SimplexEpochInfo__SealingBlockSeq__tag           = "\x40" // canoto.Tag(canoto__SimplexEpochInfo__SealingBlockSeq, canoto.Varint)
)

type canotoData_SimplexEpochInfo struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*SimplexEpochInfo) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(SimplexEpochInfo{}))
	var zero SimplexEpochInfo
	s := &canoto.Spec{
		Name: "SimplexEpochInfo",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canoto__SimplexEpochInfo__PChainReferenceHeight,
				Name:        "PChainReferenceHeight",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.PChainReferenceHeight),
			},
			{
				FieldNumber: canoto__SimplexEpochInfo__EpochNumber,
				Name:        "EpochNumber",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.EpochNumber),
			},
			{
				FieldNumber:    canoto__SimplexEpochInfo__PrevSealingBlockHash,
				Name:           "PrevSealingBlockHash",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.PrevSealingBlockHash)),
			},
			{
				FieldNumber: canoto__SimplexEpochInfo__NextPChainReferenceHeight,
				Name:        "NextPChainReferenceHeight",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.NextPChainReferenceHeight),
			},
			{
				FieldNumber: canoto__SimplexEpochInfo__PrevVMBlockSeq,
				Name:        "PrevVMBlockSeq",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.PrevVMBlockSeq),
			},
			canoto.FieldTypeFromField(
				/*type inference:*/ (zero.BlockValidationDescriptor),
				/*FieldNumber:   */ canoto__SimplexEpochInfo__BlockValidationDescriptor,
				/*Name:          */ "BlockValidationDescriptor",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			canoto.FieldTypeFromField(
				/*type inference:*/ (zero.NextEpochApprovals),
				/*FieldNumber:   */ canoto__SimplexEpochInfo__NextEpochApprovals,
				/*Name:          */ "NextEpochApprovals",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			{
				FieldNumber: canoto__SimplexEpochInfo__SealingBlockSeq,
				Name:        "SealingBlockSeq",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.SealingBlockSeq),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*SimplexEpochInfo) MakeCanoto() *SimplexEpochInfo {
	return new(SimplexEpochInfo)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *SimplexEpochInfo) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *SimplexEpochInfo) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = SimplexEpochInfo{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__SimplexEpochInfo__PChainReferenceHeight:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.PChainReferenceHeight); err != nil {
				return err
			}
			if canoto.IsZero(c.PChainReferenceHeight) {
				return canoto.ErrZeroValue
			}
		case canoto__SimplexEpochInfo__EpochNumber:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.EpochNumber); err != nil {
				return err
			}
			if canoto.IsZero(c.EpochNumber) {
				return canoto.ErrZeroValue
			}
		case canoto__SimplexEpochInfo__PrevSealingBlockHash:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.PrevSealingBlockHash)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.PrevSealingBlockHash)[:], r.B)
			if canoto.IsZero(c.PrevSealingBlockHash) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case canoto__SimplexEpochInfo__NextPChainReferenceHeight:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.NextPChainReferenceHeight); err != nil {
				return err
			}
			if canoto.IsZero(c.NextPChainReferenceHeight) {
				return canoto.ErrZeroValue
			}
		case canoto__SimplexEpochInfo__PrevVMBlockSeq:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.PrevVMBlockSeq); err != nil {
				return err
			}
			if canoto.IsZero(c.PrevVMBlockSeq) {
				return canoto.ErrZeroValue
			}
		case canoto__SimplexEpochInfo__BlockValidationDescriptor:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.BlockValidationDescriptor = canoto.MakePointer(c.BlockValidationDescriptor)
			if err := (c.BlockValidationDescriptor).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		case canoto__SimplexEpochInfo__NextEpochApprovals:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.NextEpochApprovals = canoto.MakePointer(c.NextEpochApprovals)
			if err := (c.NextEpochApprovals).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		case canoto__SimplexEpochInfo__SealingBlockSeq:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.SealingBlockSeq); err != nil {
				return err
			}
			if canoto.IsZero(c.SealingBlockSeq) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *SimplexEpochInfo) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if c.BlockValidationDescriptor != nil && !(c.BlockValidationDescriptor).ValidCanoto() {
		return false
	}
	if c.NextEpochApprovals != nil && !(c.NextEpochApprovals).ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *SimplexEpochInfo) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.PChainReferenceHeight) {
		size += uint64(len(canoto__SimplexEpochInfo__PChainReferenceHeight__tag)) + canoto.SizeUint(c.PChainReferenceHeight)
	}
	if !canoto.IsZero(c.EpochNumber) {
		size += uint64(len(canoto__SimplexEpochInfo__EpochNumber__tag)) + canoto.SizeUint(c.EpochNumber)
	}
	if !canoto.IsZero(c.PrevSealingBlockHash) {
		size += uint64(len(canoto__SimplexEpochInfo__PrevSealingBlockHash__tag)) + canoto.SizeBytes((&c.PrevSealingBlockHash)[:])
	}
	if !canoto.IsZero(c.NextPChainReferenceHeight) {
		size += uint64(len(canoto__SimplexEpochInfo__NextPChainReferenceHeight__tag)) + canoto.SizeUint(c.NextPChainReferenceHeight)
	}
	if !canoto.IsZero(c.PrevVMBlockSeq) {
		size += uint64(len(canoto__SimplexEpochInfo__PrevVMBlockSeq__tag)) + canoto.SizeUint(c.PrevVMBlockSeq)
	}
	if c.BlockValidationDescriptor != nil {
		(c.BlockValidationDescriptor).CalculateCanotoCache()
		if fieldSize := (c.BlockValidationDescriptor).CachedCanotoSize(); fieldSize != 0 {
			size += uint64(len(canoto__SimplexEpochInfo__BlockValidationDescriptor__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	if c.NextEpochApprovals != nil {
		(c.NextEpochApprovals).CalculateCanotoCache()
		if fieldSize := (c.NextEpochApprovals).CachedCanotoSize(); fieldSize != 0 {
			size += uint64(len(canoto__SimplexEpochInfo__NextEpochApprovals__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	if !canoto.IsZero(c.SealingBlockSeq) {
		size += uint64(len(canoto__SimplexEpochInfo__SealingBlockSeq__tag)) + canoto.SizeUint(c.SealingBlockSeq)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *SimplexEpochInfo) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *SimplexEpochInfo) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *SimplexEpochInfo) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.PChainReferenceHeight) {
		canoto.Append(&w, canoto__SimplexEpochInfo__PChainReferenceHeight__tag)
		canoto.AppendUint(&w, c.PChainReferenceHeight)
	}
	if !canoto.IsZero(c.EpochNumber) {
		canoto.Append(&w, canoto__SimplexEpochInfo__EpochNumber__tag)
		canoto.AppendUint(&w, c.EpochNumber)
	}
	if !canoto.IsZero(c.PrevSealingBlockHash) {
		canoto.Append(&w, canoto__SimplexEpochInfo__PrevSealingBlockHash__tag)
		canoto.AppendBytes(&w, (&c.PrevSealingBlockHash)[:])
	}
	if !canoto.IsZero(c.NextPChainReferenceHeight) {
		canoto.Append(&w, canoto__SimplexEpochInfo__NextPChainReferenceHeight__tag)
		canoto.AppendUint(&w, c.NextPChainReferenceHeight)
	}
	if !canoto.IsZero(c.PrevVMBlockSeq) {
		canoto.Append(&w, canoto__SimplexEpochInfo__PrevVMBlockSeq__tag)
		canoto.AppendUint(&w, c.PrevVMBlockSeq)
	}
	if c.BlockValidationDescriptor != nil {
		if fieldSize := (c.BlockValidationDescriptor).CachedCanotoSize(); fieldSize != 0 {
			canoto.Append(&w, canoto__SimplexEpochInfo__BlockValidationDescriptor__tag)
			canoto.AppendUint(&w, fieldSize)
			w = (c.BlockValidationDescriptor).MarshalCanotoInto(w)
		}
	}
	if c.NextEpochApprovals != nil {
		if fieldSize := (c.NextEpochApprovals).CachedCanotoSize(); fieldSize != 0 {
			canoto.Append(&w, canoto__SimplexEpochInfo__NextEpochApprovals__tag)
			canoto.AppendUint(&w, fieldSize)
			w = (c.NextEpochApprovals).MarshalCanotoInto(w)
		}
	}
	if !canoto.IsZero(c.SealingBlockSeq) {
		canoto.Append(&w, canoto__SimplexEpochInfo__SealingBlockSeq__tag)
		canoto.AppendUint(&w, c.SealingBlockSeq)
	}
	return w
}

const (
	canoto__NodeBLSMapping__NodeID = 1
	canoto__NodeBLSMapping__BLSKey = 2
	canoto__NodeBLSMapping__Weight = 3

	canoto__NodeBLSMapping__NodeID__tag = "\x0a" // canoto.Tag(canoto__NodeBLSMapping__NodeID, canoto.Len)
	canoto__NodeBLSMapping__BLSKey__tag = "\x12" // canoto.Tag(canoto__NodeBLSMapping__BLSKey, canoto.Len)
	canoto__NodeBLSMapping__Weight__tag = "\x18" // canoto.Tag(canoto__NodeBLSMapping__Weight, canoto.Varint)
)

type canotoData_NodeBLSMapping struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*NodeBLSMapping) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero NodeBLSMapping
	s := &canoto.Spec{
		Name: "NodeBLSMapping",
		Fields: []canoto.FieldType{
			{
				FieldNumber:    canoto__NodeBLSMapping__NodeID,
				Name:           "NodeID",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.NodeID)),
			},
			{
				FieldNumber: canoto__NodeBLSMapping__BLSKey,
				Name:        "BLSKey",
				OneOf:       "",
				TypeBytes:   true,
			},
			{
				FieldNumber: canoto__NodeBLSMapping__Weight,
				Name:        "Weight",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.Weight),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*NodeBLSMapping) MakeCanoto() *NodeBLSMapping {
	return new(NodeBLSMapping)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *NodeBLSMapping) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *NodeBLSMapping) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = NodeBLSMapping{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__NodeBLSMapping__NodeID:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.NodeID)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.NodeID)[:], r.B)
			if canoto.IsZero(c.NodeID) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case canoto__NodeBLSMapping__BLSKey:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.BLSKey); err != nil {
				return err
			}
			if len(c.BLSKey) == 0 {
				return canoto.ErrZeroValue
			}
		case canoto__NodeBLSMapping__Weight:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.Weight); err != nil {
				return err
			}
			if canoto.IsZero(c.Weight) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *NodeBLSMapping) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *NodeBLSMapping) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.NodeID) {
		size += uint64(len(canoto__NodeBLSMapping__NodeID__tag)) + canoto.SizeBytes((&c.NodeID)[:])
	}
	if len(c.BLSKey) != 0 {
		size += uint64(len(canoto__NodeBLSMapping__BLSKey__tag)) + canoto.SizeBytes(c.BLSKey)
	}
	if !canoto.IsZero(c.Weight) {
		size += uint64(len(canoto__NodeBLSMapping__Weight__tag)) + canoto.SizeUint(c.Weight)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *NodeBLSMapping) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *NodeBLSMapping) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *NodeBLSMapping) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.NodeID) {
		canoto.Append(&w, canoto__NodeBLSMapping__NodeID__tag)
		canoto.AppendBytes(&w, (&c.NodeID)[:])
	}
	if len(c.BLSKey) != 0 {
		canoto.Append(&w, canoto__NodeBLSMapping__BLSKey__tag)
		canoto.AppendBytes(&w, c.BLSKey)
	}
	if !canoto.IsZero(c.Weight) {
		canoto.Append(&w, canoto__NodeBLSMapping__Weight__tag)
		canoto.AppendUint(&w, c.Weight)
	}
	return w
}

const (
	canoto__BlockValidationDescriptor__AggregatedMembership = 1

	canoto__BlockValidationDescriptor__AggregatedMembership__tag = "\x0a" // canoto.Tag(canoto__BlockValidationDescriptor__AggregatedMembership, canoto.Len)
)

type canotoData_BlockValidationDescriptor struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*BlockValidationDescriptor) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(BlockValidationDescriptor{}))
	var zero BlockValidationDescriptor
	s := &canoto.Spec{
		Name: "BlockValidationDescriptor",
		Fields: []canoto.FieldType{
			canoto.FieldTypeFromField(
				/*type inference:*/ (&zero.AggregatedMembership),
				/*FieldNumber:   */ canoto__BlockValidationDescriptor__AggregatedMembership,
				/*Name:          */ "AggregatedMembership",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*BlockValidationDescriptor) MakeCanoto() *BlockValidationDescriptor {
	return new(BlockValidationDescriptor)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *BlockValidationDescriptor) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *BlockValidationDescriptor) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = BlockValidationDescriptor{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__BlockValidationDescriptor__AggregatedMembership:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			if err := (&c.AggregatedMembership).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *BlockValidationDescriptor) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if !(&c.AggregatedMembership).ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *BlockValidationDescriptor) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	(&c.AggregatedMembership).CalculateCanotoCache()
	if fieldSize := (&c.AggregatedMembership).CachedCanotoSize(); fieldSize != 0 {
		size += uint64(len(canoto__BlockValidationDescriptor__AggregatedMembership__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *BlockValidationDescriptor) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *BlockValidationDescriptor) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *BlockValidationDescriptor) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if fieldSize := (&c.AggregatedMembership).CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__BlockValidationDescriptor__AggregatedMembership__tag)
		canoto.AppendUint(&w, fieldSize)
		w = (&c.AggregatedMembership).MarshalCanotoInto(w)
	}
	return w
}

const (
	canoto__AggregatedMembership__Members = 1

	canoto__AggregatedMembership__Members__tag = "\x0a" // canoto.Tag(canoto__AggregatedMembership__Members, canoto.Len)
)

type canotoData_AggregatedMembership struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*AggregatedMembership) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(AggregatedMembership{}))
	var zero AggregatedMembership
	s := &canoto.Spec{
		Name: "AggregatedMembership",
		Fields: []canoto.FieldType{
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntryNilPointer(zero.Members)),
				/*FieldNumber:   */ canoto__AggregatedMembership__Members,
				/*Name:          */ "Members",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*AggregatedMembership) MakeCanoto() *AggregatedMembership {
	return new(AggregatedMembership)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *AggregatedMembership) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *AggregatedMembership) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = AggregatedMembership{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__AggregatedMembership__Members:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__AggregatedMembership__Members__tag)
			if err != nil {
				return err
			}

			c.Members = canoto.MakeSlice(c.Members, countMinus1+1)
			field := c.Members
			additionalField := field[1:]
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				if err := (&field[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range additionalField {
				r.B = r.B[len(canoto__AggregatedMembership__Members__tag):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				if err := (&additionalField[i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *AggregatedMembership) ValidCanoto() bool {
	if c == nil {
		return true
	}
	{
		field := c.Members
		for i := range field {
			if !(&field[i]).ValidCanoto() {
				return false
			}
		}
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *AggregatedMembership) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	{
		field := c.Members
		for i := range field {
			(&field[i]).CalculateCanotoCache()
			fieldSize := (&field[i]).CachedCanotoSize()
			size += uint64(len(canoto__AggregatedMembership__Members__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *AggregatedMembership) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AggregatedMembership) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AggregatedMembership) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	{
		field := c.Members
		for i := range field {
			canoto.Append(&w, canoto__AggregatedMembership__Members__tag)
			canoto.AppendUint(&w, (&field[i]).CachedCanotoSize())
			w = (&field[i]).MarshalCanotoInto(w)
		}
	}
	return w
}

const (
	canoto__NextEpochApprovals__NodeIDs   = 1
	canoto__NextEpochApprovals__Signature = 2

	canoto__NextEpochApprovals__NodeIDs__tag   = "\x0a" // canoto.Tag(canoto__NextEpochApprovals__NodeIDs, canoto.Len)
	canoto__NextEpochApprovals__Signature__tag = "\x12" // canoto.Tag(canoto__NextEpochApprovals__Signature, canoto.Len)
)

type canotoData_NextEpochApprovals struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*NextEpochApprovals) CanotoSpec(...reflect.Type) *canoto.Spec {
	s := &canoto.Spec{
		Name: "NextEpochApprovals",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canoto__NextEpochApprovals__NodeIDs,
				Name:        "NodeIDs",
				OneOf:       "",
				TypeBytes:   true,
			},
			{
				FieldNumber: canoto__NextEpochApprovals__Signature,
				Name:        "Signature",
				OneOf:       "",
				TypeBytes:   true,
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*NextEpochApprovals) MakeCanoto() *NextEpochApprovals {
	return new(NextEpochApprovals)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *NextEpochApprovals) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *NextEpochApprovals) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = NextEpochApprovals{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__NextEpochApprovals__NodeIDs:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.NodeIDs); err != nil {
				return err
			}
			if len(c.NodeIDs) == 0 {
				return canoto.ErrZeroValue
			}
		case canoto__NextEpochApprovals__Signature:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.Signature); err != nil {
				return err
			}
			if len(c.Signature) == 0 {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *NextEpochApprovals) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *NextEpochApprovals) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if len(c.NodeIDs) != 0 {
		size += uint64(len(canoto__NextEpochApprovals__NodeIDs__tag)) + canoto.SizeBytes(c.NodeIDs)
	}
	if len(c.Signature) != 0 {
		size += uint64(len(canoto__NextEpochApprovals__Signature__tag)) + canoto.SizeBytes(c.Signature)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *NextEpochApprovals) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *NextEpochApprovals) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *NextEpochApprovals) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if len(c.NodeIDs) != 0 {
		canoto.Append(&w, canoto__NextEpochApprovals__NodeIDs__tag)
		canoto.AppendBytes(&w, c.NodeIDs)
	}
	if len(c.Signature) != 0 {
		canoto.Append(&w, canoto__NextEpochApprovals__Signature__tag)
		canoto.AppendBytes(&w, c.Signature)
	}
	return w
}

const (
	canoto__ValidatorSetApproval__NodeID           = 1
	canoto__ValidatorSetApproval__AuxInfoSeqDigest = 2
	canoto__ValidatorSetApproval__PChainHeight     = 3
	canoto__ValidatorSetApproval__Signature        = 4

	canoto__ValidatorSetApproval__NodeID__tag           = "\x0a" // canoto.Tag(canoto__ValidatorSetApproval__NodeID, canoto.Len)
	canoto__ValidatorSetApproval__AuxInfoSeqDigest__tag = "\x12" // canoto.Tag(canoto__ValidatorSetApproval__AuxInfoSeqDigest, canoto.Len)
	canoto__ValidatorSetApproval__PChainHeight__tag     = "\x18" // canoto.Tag(canoto__ValidatorSetApproval__PChainHeight, canoto.Varint)
	canoto__ValidatorSetApproval__Signature__tag        = "\x22" // canoto.Tag(canoto__ValidatorSetApproval__Signature, canoto.Len)
)

type canotoData_ValidatorSetApproval struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*ValidatorSetApproval) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero ValidatorSetApproval
	s := &canoto.Spec{
		Name: "ValidatorSetApproval",
		Fields: []canoto.FieldType{
			{
				FieldNumber:    canoto__ValidatorSetApproval__NodeID,
				Name:           "NodeID",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.NodeID)),
			},
			{
				FieldNumber:    canoto__ValidatorSetApproval__AuxInfoSeqDigest,
				Name:           "AuxInfoSeqDigest",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.AuxInfoSeqDigest)),
			},
			{
				FieldNumber: canoto__ValidatorSetApproval__PChainHeight,
				Name:        "PChainHeight",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.PChainHeight),
			},
			{
				FieldNumber: canoto__ValidatorSetApproval__Signature,
				Name:        "Signature",
				OneOf:       "",
				TypeBytes:   true,
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*ValidatorSetApproval) MakeCanoto() *ValidatorSetApproval {
	return new(ValidatorSetApproval)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *ValidatorSetApproval) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *ValidatorSetApproval) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = ValidatorSetApproval{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__ValidatorSetApproval__NodeID:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.NodeID)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.NodeID)[:], r.B)
			if canoto.IsZero(c.NodeID) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case canoto__ValidatorSetApproval__AuxInfoSeqDigest:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.AuxInfoSeqDigest)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.AuxInfoSeqDigest)[:], r.B)
			if canoto.IsZero(c.AuxInfoSeqDigest) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case canoto__ValidatorSetApproval__PChainHeight:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.PChainHeight); err != nil {
				return err
			}
			if canoto.IsZero(c.PChainHeight) {
				return canoto.ErrZeroValue
			}
		case canoto__ValidatorSetApproval__Signature:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.Signature); err != nil {
				return err
			}
			if len(c.Signature) == 0 {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *ValidatorSetApproval) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *ValidatorSetApproval) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.NodeID) {
		size += uint64(len(canoto__ValidatorSetApproval__NodeID__tag)) + canoto.SizeBytes((&c.NodeID)[:])
	}
	if !canoto.IsZero(c.AuxInfoSeqDigest) {
		size += uint64(len(canoto__ValidatorSetApproval__AuxInfoSeqDigest__tag)) + canoto.SizeBytes((&c.AuxInfoSeqDigest)[:])
	}
	if !canoto.IsZero(c.PChainHeight) {
		size += uint64(len(canoto__ValidatorSetApproval__PChainHeight__tag)) + canoto.SizeUint(c.PChainHeight)
	}
	if len(c.Signature) != 0 {
		size += uint64(len(canoto__ValidatorSetApproval__Signature__tag)) + canoto.SizeBytes(c.Signature)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *ValidatorSetApproval) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *ValidatorSetApproval) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *ValidatorSetApproval) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.NodeID) {
		canoto.Append(&w, canoto__ValidatorSetApproval__NodeID__tag)
		canoto.AppendBytes(&w, (&c.NodeID)[:])
	}
	if !canoto.IsZero(c.AuxInfoSeqDigest) {
		canoto.Append(&w, canoto__ValidatorSetApproval__AuxInfoSeqDigest__tag)
		canoto.AppendBytes(&w, (&c.AuxInfoSeqDigest)[:])
	}
	if !canoto.IsZero(c.PChainHeight) {
		canoto.Append(&w, canoto__ValidatorSetApproval__PChainHeight__tag)
		canoto.AppendUint(&w, c.PChainHeight)
	}
	if len(c.Signature) != 0 {
		canoto.Append(&w, canoto__ValidatorSetApproval__Signature__tag)
		canoto.AppendBytes(&w, c.Signature)
	}
	return w
}

const (
	canoto__StateMachineBlockPreImage__InnerBlockHash = 1
	canoto__StateMachineBlockPreImage__Metadata       = 2

	canoto__StateMachineBlockPreImage__InnerBlockHash__tag = "\x0a" // canoto.Tag(canoto__StateMachineBlockPreImage__InnerBlockHash, canoto.Len)
	canoto__StateMachineBlockPreImage__Metadata__tag       = "\x12" // canoto.Tag(canoto__StateMachineBlockPreImage__Metadata, canoto.Len)
)

type canotoData_StateMachineBlockPreImage struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*StateMachineBlockPreImage) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(StateMachineBlockPreImage{}))
	var zero StateMachineBlockPreImage
	s := &canoto.Spec{
		Name: "StateMachineBlockPreImage",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canoto__StateMachineBlockPreImage__InnerBlockHash,
				Name:        "InnerBlockHash",
				OneOf:       "",
				TypeBytes:   true,
			},
			canoto.FieldTypeFromField(
				/*type inference:*/ (&zero.Metadata),
				/*FieldNumber:   */ canoto__StateMachineBlockPreImage__Metadata,
				/*Name:          */ "Metadata",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*StateMachineBlockPreImage) MakeCanoto() *StateMachineBlockPreImage {
	return new(StateMachineBlockPreImage)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *StateMachineBlockPreImage) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *StateMachineBlockPreImage) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = StateMachineBlockPreImage{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__StateMachineBlockPreImage__InnerBlockHash:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.InnerBlockHash); err != nil {
				return err
			}
			if len(c.InnerBlockHash) == 0 {
				return canoto.ErrZeroValue
			}
		case canoto__StateMachineBlockPreImage__Metadata:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			if err := (&c.Metadata).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *StateMachineBlockPreImage) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if !(&c.Metadata).ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *StateMachineBlockPreImage) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if len(c.InnerBlockHash) != 0 {
		size += uint64(len(canoto__StateMachineBlockPreImage__InnerBlockHash__tag)) + canoto.SizeBytes(c.InnerBlockHash)
	}
	(&c.Metadata).CalculateCanotoCache()
	if fieldSize := (&c.Metadata).CachedCanotoSize(); fieldSize != 0 {
		size += uint64(len(canoto__StateMachineBlockPreImage__Metadata__tag)) + canoto.SizeUint(fieldSize) + fieldSize
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *StateMachineBlockPreImage) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *StateMachineBlockPreImage) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *StateMachineBlockPreImage) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if len(c.InnerBlockHash) != 0 {
		canoto.Append(&w, canoto__StateMachineBlockPreImage__InnerBlockHash__tag)
		canoto.AppendBytes(&w, c.InnerBlockHash)
	}
	if fieldSize := (&c.Metadata).CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(&w, canoto__StateMachineBlockPreImage__Metadata__tag)
		canoto.AppendUint(&w, fieldSize)
		w = (&c.Metadata).MarshalCanotoInto(w)
	}
	return w
}
